CREATE TABLE IF NOT EXISTS "USER"
(
    ID       SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL    VARCHAR(255) NOT NULL UNIQUE,
    ROLE     VARCHAR(5)   NOT NULL DEFAULT 'USER' CHECK (ROLE IN ('USER', 'ADMIN')),
    DETAILS  TEXT         NULL,
    AVATAR   TEXT         NULL,
    BANNER   TEXT         NULL,
    CONTACT  TEXT         NULL
);

CREATE TABLE IF NOT EXISTS "MODEL"
(
    ID                            SERIAL PRIMARY KEY,
    FILE                          TEXT       NOT NULL,
    FORMAT                        VARCHAR(5) NOT NULL DEFAULT 'obj' CHECK (FORMAT IN ('fbx', 'glb', 'gltf', 'obj')),
    PREVIEW                       TEXT       NOT NULL,
    BACKGROUND_COLOR              VARCHAR(7) NOT NULL,
    AMBIENT_LIGHT_INTENSITY       DECIMAL    NOT NULL,
    DIRECTIONAL_LIGHT_INTENSITY   DECIMAL    NOT NULL,
    HEMISPHERE_LIGHT_INTENSITY    DECIMAL    NOT NULL,
    HEMISPHERE_LIGHT_GROUND_COLOR VARCHAR(7) NOT NULL
);


CREATE TABLE IF NOT EXISTS "ART"
(
    ID          SERIAL PRIMARY KEY,
    TITLE       TEXT                                NOT NULL,
    MODEL_ID    INT                                 NOT NULL,
    AUTHOR_ID   INT                                 NOT NULL,
    DESCRIPTION TEXT                                NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TAG         TEXT ARRAY                          NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES "USER" (ID),
    FOREIGN KEY (MODEL_ID) REFERENCES "MODEL" (ID)
);

CREATE TABLE IF NOT EXISTS "WATCHLIST"
(
    ART_ID  INT NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (ART_ID, USER_ID),
    FOREIGN KEY (ART_ID) REFERENCES "ART" (ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE IF NOT EXISTS "COMMENT"
(
    ID          SERIAL PRIMARY KEY,
    ART_ID      INT                                 NOT NULL,
    USER_ID     INT                                 NOT NULL,
    COMMENT     TEXT                                NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    FOREIGN KEY (ART_ID) REFERENCES "ART" (ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

CREATE TABLE IF NOT EXISTS "RATING"
(
    ART_ID      INT                                 NOT NULL,
    USER_ID     INT                                 NOT NULL,
    RATING      INT                                 NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (ART_ID, USER_ID),
    FOREIGN KEY (ART_ID) REFERENCES "ART" (ID),
    FOREIGN KEY (USER_ID) REFERENCES "USER" (ID)
);

DROP TABLE IF EXISTS "COMMENT";
DROP TABLE IF EXISTS "RATING";
DROP TABLE IF EXISTS "WATCHLIST";
DROP TABLE IF EXISTS "ATR";
DROP TABLE IF EXISTS "MODEL";
DROP TABLE IF EXISTS "USER";